//! Runtime implementation layer for the desktop API.
//!
//! `commands.rs` retains only thin Tauri command entry points. This module handles parameter
//! validation, system capability calls, and event state without mixing the desktop API into the long-lived `bt.call()` VM channel.

use std::collections::HashMap;
use std::sync::{Mutex, MutexGuard};
use tauri::tray::TrayIcon;

/// Tray menu click event name.
pub const TRAY_MENU_CLICK_EVENT: &str = "bt://tray/menu_click";

/// File-drop event name.
pub const DRAG_FILES_EVENT: &str = "bt://drag/files";

/// File watcher change event name.
pub const WATCH_PATH_EVENT: &str = "bt://app/watch_path";

/// Window close request event name.
pub const WINDOW_CLOSE_REQUESTED_EVENT: &str = "bt://window/close_requested";

/// Maximum number of file watchers retained for one window.
const MAX_PATH_WATCHERS: usize = 64;

/// Shared runtime state for the desktop API.
pub struct ApiState {
    /// Desktop state retained across commands.
    inner: Mutex<ApiStateInner>,
}

/// Contents of the shared desktop API runtime state.
struct ApiStateInner {
    /// Current behavior of the window close button.
    close_mode: CloseMode,
    /// Current tray icon handle; `None` means the tray is disabled.
    tray: Option<TrayIcon>,
    /// Desktop file watcher handles keyed by stable IDs generated by the frontend.
    watches: HashMap<String, watch::PathWatcher>,
    /// Whether the page manages asynchronous cleanup before exit.
    close_intercept: bool,
    /// One-shot flag allowing the next close request after page cleanup completes.
    allow_close_once: bool,
}

/// Behavior after the window close button is clicked.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CloseMode {
    /// Exit the application immediately.
    Exit,
    /// Hide the window while keeping the application running.
    Hide,
    /// Hide the window and rely on the tray menu to restore or exit.
    Tray,
}

impl ApiState {
    /// Creates the default desktop API state.
    pub fn new() -> Self {
        Self {
            inner: Mutex::new(ApiStateInner {
                close_mode: CloseMode::Exit,
                tray: None,
                watches: HashMap::with_capacity(4),
                close_intercept: false,
                allow_close_once: false,
            }),
        }
    }

    /// Returns the current close mode.
    pub fn close_mode(&self) -> Result<CloseMode, String> {
        Ok(self.lock()?.close_mode)
    }

    /// Sets the current close mode.
    pub fn set_close_mode(&self, mode: CloseMode) -> Result<(), String> {
        self.lock()?.close_mode = mode;
        Ok(())
    }

    /// Returns whether the tray is currently enabled.
    pub fn has_tray(&self) -> Result<bool, String> {
        Ok(self.lock()?.tray.is_some())
    }

    /// Stores a new tray icon handle, releasing the old handle when replaced.
    pub fn set_tray(&self, tray: TrayIcon) -> Result<(), String> {
        self.lock()?.tray = Some(tray);
        Ok(())
    }

    /// Disables the tray icon and releases its handle.
    pub fn take_tray(&self) -> Result<Option<TrayIcon>, String> {
        Ok(self.lock()?.tray.take())
    }

    /// Applies a lightweight update to the current tray handle.
    pub fn with_tray<T>(
        &self,
        action: impl FnOnce(&TrayIcon) -> Result<T, String>,
    ) -> Result<T, String> {
        let guard = self.lock()?;
        let Some(tray) = guard.tray.as_ref() else {
            return Err("The tray is not currently enabled".to_string());
        };
        action(tray)
    }

    /// Stores a file watcher by ID; safely replaces matching IDs and rejects additions beyond the limit.
    pub fn set_watch(&self, watch_id: String, watch: watch::PathWatcher) -> Result<(), String> {
        if watch_id.is_empty()
            || watch_id.len() > 128
            || !watch_id
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
        {
            return Err(
                "watch_id may contain only letters, digits, hyphens, and underscores and cannot exceed 128 characters".to_string(),
            );
        }
        let mut inner = self.lock()?;
        if !inner.watches.contains_key(&watch_id) && inner.watches.len() >= MAX_PATH_WATCHERS {
            return Err(format!(
                "File watcher count cannot exceed {}",
                MAX_PATH_WATCHERS
            ));
        }
        inner.watches.insert(watch_id, watch);
        Ok(())
    }

    /// Stops and releases the specified file watcher, or all watchers when no ID is provided.
    pub fn take_watch(&self, watch_id: Option<&str>) -> Result<Vec<watch::PathWatcher>, String> {
        let mut inner = self.lock()?;
        if let Some(watch_id) = watch_id {
            return Ok(inner.watches.remove(watch_id).into_iter().collect());
        }
        Ok(inner.watches.drain().map(|(_, watch)| watch).collect())
    }

    /// Enables or disables page exit interception and clears the one-shot bypass when disabling it.
    pub fn set_close_intercept(&self, enabled: bool) -> Result<(), String> {
        let mut inner = self.lock()?;
        inner.close_intercept = enabled;
        if !enabled {
            inner.allow_close_once = false;
        }
        Ok(())
    }

    /// Returns whether the page manages cleanup before exit.
    pub fn close_intercept(&self) -> Result<bool, String> {
        Ok(self.lock()?.close_intercept)
    }

    /// Marks asynchronous page cleanup complete, allowing the next close request to exit directly.
    pub fn allow_close_once(&self) -> Result<(), String> {
        self.lock()?.allow_close_once = true;
        Ok(())
    }

    /// Reads and consumes the one-shot close bypass.
    pub fn take_close_allowance(&self) -> Result<bool, String> {
        let mut inner = self.lock()?;
        let allowed = inner.allow_close_once;
        inner.allow_close_once = false;
        Ok(allowed)
    }

    /// Locks shared state and converts a poisoned lock into an error.
    fn lock(&self) -> Result<MutexGuard<'_, ApiStateInner>, String> {
        self.inner
            .lock()
            .map_err(|_| "Desktop API state is corrupted".to_string())
    }
}

/// Adds context to an underlying error.
pub fn map_error(context: &str, err: impl std::fmt::Display) -> String {
    format!("{} failed: {}", context, err)
}

/// Validates a required string parameter.
pub fn required_text(value: String, name: &str) -> Result<String, String> {
    if value.trim().is_empty() {
        Err(format!("{} cannot be empty", name))
    } else {
        Ok(value)
    }
}

/// Converts a path to absolute path text.
pub fn absolute_path_text(path: std::path::PathBuf) -> Result<String, String> {
    let path = if path.is_absolute() {
        path
    } else {
        std::env::current_dir()
            .map_err(|err| map_error("Read current directory", err))?
            .join(path)
    };
    Ok(crate::path::path_text(&path))
}

#[cfg(test)]
mod tests {
    use super::ApiState;

    /// The close-interception bypass must be consumed once so later closes cannot skip page cleanup.
    #[test]
    fn close_allowance_is_one_shot() {
        let state = ApiState::new();
        state.set_close_intercept(true).unwrap();
        assert!(state.close_intercept().unwrap());
        assert!(!state.take_close_allowance().unwrap());

        state.allow_close_once().unwrap();
        assert!(state.take_close_allowance().unwrap());
        assert!(!state.take_close_allowance().unwrap());

        state.set_close_intercept(false).unwrap();
        assert!(!state.close_intercept().unwrap());
    }
}

pub mod app;
pub mod clipboard;
pub mod dialog;
pub mod drag;
pub mod notify;
pub mod production;
pub mod screen;
pub mod shortcut;
pub mod tray;
pub mod watch;
pub mod window;
