//! Production desktop API.
//!
//! This module consolidates streaming HTTP, application credentials, workspace files,
//! subprocesses, and application-owned data in the native Rust layer. All long-lived
//! collections have fixed limits. Stream cancellation closes the event gate before notifying
//! the request task, preventing dispatch after cancellation. Path and cleanup operations use
//! canonical paths and cannot escape their boundaries through textual prefixes.

use futures_util::StreamExt;
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::fs::{self, File, OpenOptions};
use std::io::{Read, Write};
use std::path::{Component, Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::atomic::{AtomicBool, AtomicI32, AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};
use std::thread;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};
use tauri::WebviewWindow;
use tokio::sync::watch;
use uuid::Uuid;

/// Streaming HTTP DOM event name.
pub const HTTP_STREAM_EVENT: &str = "bt://http/stream";
/// Native process DOM event name.
pub const PROCESS_EVENT: &str = "bt://process/event";
/// BT backend call completion event name.
pub const BACKEND_EVENT: &str = "bt://backend/event";

/// Maximum number of concurrent streaming requests.
const MAX_STREAMS: usize = 8;
/// Maximum bytes allowed for one streaming response.
const MAX_STREAM_BYTES: usize = 4_000_000;
/// Maximum chunk events dispatched for one response.
const MAX_STREAM_CHUNKS: usize = 16_384;
/// Maximum number of registered workspaces.
const MAX_WORKSPACES: usize = 8;
/// Maximum bytes per workspace read.
const MAX_WORKSPACE_READ_BYTES: usize = 4 * 1024 * 1024;
/// Maximum entries per workspace listing.
const MAX_WORKSPACE_ENTRIES: usize = 4_096;
/// Maximum number of registered native processes.
const MAX_PROCESSES: usize = 32;
/// Default retention limit for each process output stream.
const DEFAULT_PROCESS_OUTPUT_LIMIT: usize = 64 * 1024;
/// Maximum retention limit for each process output stream.
const MAX_PROCESS_OUTPUT_LIMIT: usize = 1024 * 1024;
/// Cleanup confirmation ticket lifetime.
const CLEANUP_TICKET_TTL: Duration = Duration::from_secs(120);

/// Shared state for the production desktop API.
pub struct ProductionState {
    /// Internal state that can safely move into async tasks and output threads.
    inner: Arc<Mutex<ProductionStateInner>>,
}

/// Bounded internal state for the production desktop API.
struct ProductionStateInner {
    /// Streaming requests currently allowed to dispatch events to the page.
    streams: HashMap<String, StreamControl>,
    /// Canonical workspaces registered by the current window.
    workspaces: HashMap<String, WorkspaceRoot>,
    /// Processes started by the current window that can still be queried or stopped precisely.
    processes: HashMap<String, Arc<ManagedProcess>>,
    /// Short-lived ticket from the most recent data cleanup preview.
    cleanup_ticket: Option<CleanupTicket>,
}

/// Cancellation channel and event sequence for one streaming request.
struct StreamControl {
    /// Cancellation notification; removing the map entry also ends the receiver immediately.
    cancel: watch::Sender<bool>,
    /// Next event sequence number.
    sequence: u64,
}

/// Canonical workspace root.
#[derive(Clone)]
struct WorkspaceRoot {
    /// Absolute root resolved by the operating system.
    root: PathBuf,
}

/// Secondary confirmation ticket for data cleanup.
struct CleanupTicket {
    /// The ticket is valid only for the application data root that created it.
    app_name: String,
    /// Unpredictable one-time confirmation value.
    token: String,
    /// Time when the ticket was created.
    created_at: Instant,
}

/// Plaintext JSON application credential file; the caller explicitly selects this format for
/// easier migration and manual maintenance.
#[derive(Deserialize, Serialize)]
struct CredentialFile {
    /// File format version.
    schema: u32,
    /// Stable credential ID supplied by the caller.
    credential_id: String,
    /// Credential plaintext stored verbatim.
    api_key: String,
}

/// Streaming request options.
#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HttpStreamOptions {
    /// Request ID generated by the page so listeners can be installed before startup.
    pub request_id: String,
    /// HTTP request URL; only http/https is allowed.
    pub url: String,
    /// HTTP method; streaming calls with a request body typically use POST.
    #[serde(default = "default_post_method")]
    pub method: String,
    /// Non-sensitive request headers; Authorization and Cookie must be managed by the native layer.
    #[serde(default)]
    pub headers: HashMap<String, String>,
    /// UTF-8 request body.
    #[serde(default)]
    pub body: String,
    /// Application credential ID; an empty value omits Authorization.
    #[serde(default)]
    pub credential_id: String,
    /// Total request timeout in milliseconds.
    #[serde(default = "default_http_timeout_ms")]
    pub timeout_ms: u64,
    /// Response body byte limit; the request ends immediately if exceeded.
    #[serde(default = "default_stream_bytes")]
    pub max_response_bytes: usize,
}

/// Streaming request startup result.
#[derive(Clone, Debug, Serialize)]
pub struct HttpStreamStart {
    /// Stable request ID.
    pub request_id: String,
    /// Concurrent request limit for the current process.
    pub active_limit: usize,
    /// Effective response byte limit for the current request.
    pub max_response_bytes: usize,
}

/// Streaming event dispatched to the page.
#[derive(Clone, Debug, Serialize)]
struct HttpStreamPayload {
    /// Request ID.
    request_id: String,
    /// Strictly increasing event sequence number.
    sequence: u64,
    /// start, headers, chunk, done, error, or cancelled.
    kind: String,
    /// HTTP status code; 0 until response headers arrive.
    status: u16,
    /// Current chunk text or the final complete response text.
    data: String,
    /// Redacted user-visible error.
    message: String,
    /// Response bytes received so far.
    received_bytes: usize,
}

/// Workspace open result.
#[derive(Clone, Debug, Serialize)]
pub struct WorkspaceOpenResult {
    /// Short-lived workspace ID generated by the native layer.
    pub workspace_id: String,
    /// Canonical root directory.
    pub root: String,
}

/// Workspace directory entry.
#[derive(Clone, Debug, Serialize)]
pub struct WorkspaceEntry {
    /// Workspace-relative path using forward slashes.
    pub path: String,
    /// file, directory, or symlink.
    pub kind: String,
    /// File size in bytes; 0 for directories and links.
    pub bytes: u64,
}

/// Workspace text read result.
#[derive(Clone, Debug, Serialize)]
pub struct WorkspaceReadResult {
    /// Canonical workspace-relative path.
    pub path: String,
    /// UTF-8 text.
    pub content: String,
    /// Original byte count.
    pub bytes: usize,
    /// Content SHA-256.
    pub sha256: String,
}

/// Workspace atomic write result.
#[derive(Clone, Debug, Serialize)]
pub struct WorkspaceWriteResult {
    /// Canonical workspace-relative path.
    pub path: String,
    /// New content byte count.
    pub bytes: usize,
    /// New content SHA-256.
    pub sha256: String,
    /// Previous content SHA-256; null for a new file.
    pub previous_sha256: Option<String>,
}

/// Native process startup options.
#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProcessStartOptions {
    /// Owning caller task ID.
    pub task_id: String,
    /// Program path or program name, invoked without a shell.
    pub program: String,
    /// Argument array passed verbatim to the program.
    #[serde(default)]
    pub args: Vec<String>,
    /// Registered workspace ID.
    pub workspace_id: String,
    /// Workspace-relative current directory; empty means the workspace root.
    #[serde(default)]
    pub cwd: String,
    /// Environment variables injected only into the target subprocess.
    #[serde(default)]
    pub environment: HashMap<String, String>,
    /// Timeout in milliseconds; 0 disables automatic timeout.
    #[serde(default)]
    pub timeout_ms: u64,
    /// Per-stream byte retention limit for stdout and stderr.
    #[serde(default = "default_process_output_limit")]
    pub output_limit: usize,
}

/// Native process runtime record.
struct ManagedProcess {
    /// Immutable native process metadata.
    meta: ProcessMeta,
    /// Child process handle; stopping and monitoring must verify its PID.
    child: Mutex<Child>,
    /// Whether the process is still running.
    running: AtomicBool,
    /// Exit code; i32::MIN until the process exits.
    exit_code: AtomicI32,
    /// Whether termination was triggered by a timeout.
    timed_out: AtomicBool,
    /// Bounded stdout buffer.
    stdout: Mutex<Vec<u8>>,
    /// Bounded stderr buffer.
    stderr: Mutex<Vec<u8>>,
    /// Number of stdout bytes truncated.
    stdout_dropped: AtomicUsize,
    /// Number of stderr bytes truncated.
    stderr_dropped: AtomicUsize,
}

/// Immutable native process metadata.
struct ProcessMeta {
    /// Native record ID.
    id: String,
    /// Owning task ID.
    task_id: String,
    /// Identity value derived from the PID and startup information.
    identity: String,
    /// Operating-system PID.
    pid: u32,
    /// Program text.
    program: String,
    /// Argument array.
    args: Vec<String>,
    /// Canonical current directory.
    cwd: String,
    /// Startup timestamp in milliseconds.
    started_at: u128,
    /// Per-stream output retention limit.
    output_limit: usize,
}

/// Native process snapshot returned to the page.
#[derive(Clone, Debug, Serialize)]
pub struct ProcessSnapshot {
    /// Native record ID.
    pub id: String,
    /// Owning task ID.
    pub task_id: String,
    /// PID identity value, which must be returned verbatim when stopping the process.
    pub identity: String,
    /// Operating-system PID.
    pub pid: u32,
    /// Program text.
    pub program: String,
    /// Argument array.
    pub args: Vec<String>,
    /// Canonical current directory.
    pub cwd: String,
    /// Whether the process is still running.
    pub running: bool,
    /// Exit code; null while running.
    pub exit_code: Option<i32>,
    /// Whether the process timed out.
    pub timed_out: bool,
    /// Bounded stdout text.
    pub stdout: String,
    /// Bounded stderr text.
    pub stderr: String,
    /// Number of discarded stdout bytes.
    pub stdout_dropped: usize,
    /// Number of discarded stderr bytes.
    pub stderr_dropped: usize,
    /// Startup timestamp in milliseconds.
    pub started_at: u128,
}

/// Native process event.
#[derive(Clone, Debug, Serialize)]
struct ProcessEventPayload {
    /// Process record ID.
    process_id: String,
    /// Owning task ID.
    task_id: String,
    /// start, stdout, stderr, exit, timeout, or stopped.
    kind: String,
    /// Bounded output fragment added by this event.
    data: String,
    /// Current PID.
    pid: u32,
}

/// Data cleanup preview result.
#[derive(Clone, Debug, Serialize)]
pub struct CleanupPreview {
    /// One-time secondary confirmation ticket.
    pub confirm_token: String,
    /// Fixed categories to be cleared.
    pub categories: Vec<CleanupCategory>,
    /// Total file count.
    pub total_files: usize,
    /// Total byte count.
    pub total_bytes: u64,
    /// Explicit statement that user projects will not be touched.
    pub boundary: String,
}

/// One data cleanup category.
#[derive(Clone, Debug, Serialize)]
pub struct CleanupCategory {
    /// knowledge_cache, sessions, logs, temp, or credentials.
    pub name: String,
    /// Number of files in this category.
    pub files: usize,
    /// Total bytes in this category.
    pub bytes: u64,
}

/// Data cleanup result.
#[derive(Clone, Debug, Serialize)]
pub struct CleanupResult {
    /// Cleared categories.
    pub cleared: Vec<String>,
    /// File count before cleanup.
    pub removed_files: usize,
    /// Byte count before cleanup.
    pub removed_bytes: u64,
    /// User project protection result.
    pub workspace_untouched: bool,
}

impl ProductionState {
    /// Creates an empty production API state.
    pub fn new() -> Self {
        Self {
            inner: Arc::new(Mutex::new(ProductionStateInner {
                streams: HashMap::with_capacity(MAX_STREAMS),
                workspaces: HashMap::with_capacity(MAX_WORKSPACES),
                processes: HashMap::with_capacity(MAX_PROCESSES),
                cleanup_ticket: None,
            })),
        }
    }

    /// Starts a real streaming HTTP request and immediately returns its request ID.
    pub fn start_stream(
        &self,
        window: WebviewWindow,
        app_name: &str,
        mut options: HttpStreamOptions,
    ) -> Result<HttpStreamStart, String> {
        validate_stream_options(&options)?;
        options.max_response_bytes = options.max_response_bytes.clamp(1, MAX_STREAM_BYTES);
        let app_name = sanitize_app_name(app_name)?;
        let (cancel, cancel_rx) = watch::channel(false);
        {
            let mut inner = self.lock()?;
            if inner.streams.len() >= MAX_STREAMS {
                return Err(format!(
                    "At most {} streaming requests may run concurrently",
                    MAX_STREAMS
                ));
            }
            if inner.streams.contains_key(&options.request_id) {
                return Err("Streaming request_id already exists".to_string());
            }
            inner.streams.insert(
                options.request_id.clone(),
                StreamControl {
                    cancel,
                    sequence: 0,
                },
            );
        }

        let request_id = options.request_id.clone();
        let max_response_bytes = options.max_response_bytes;
        let shared = Arc::clone(&self.inner);
        tauri::async_runtime::spawn(async move {
            run_stream_request(shared, window, app_name, options, cancel_rx).await;
        });
        Ok(HttpStreamStart {
            request_id,
            active_limit: MAX_STREAMS,
            max_response_bytes,
        })
    }

    /// Cancels a request, notifying the async task only after removing the event gate.
    pub fn cancel_stream(&self, window: &WebviewWindow, request_id: &str) -> Result<bool, String> {
        validate_identifier(request_id, "request_id")?;
        let control = self.lock()?.streams.remove(request_id);
        let Some(control) = control else {
            return Ok(false);
        };
        let _ = control.cancel.send(true);
        dispatch_dom_event(
            window,
            HTTP_STREAM_EVENT,
            &HttpStreamPayload {
                request_id: request_id.to_string(),
                sequence: control.sequence + 1,
                kind: "cancelled".to_string(),
                status: 0,
                data: String::new(),
                message: "Request cancelled; subsequent events have been disabled".to_string(),
                received_bytes: 0,
            },
        );
        Ok(true)
    }

    /// Registers a canonical workspace root and returns a short-lived ID.
    pub fn open_workspace(&self, root: String) -> Result<WorkspaceOpenResult, String> {
        let root = fs::canonicalize(PathBuf::from(root.trim()))
            .map_err(|err| format!("Failed to resolve the canonical workspace path: {}", err))?;
        if !root.is_dir() {
            return Err("Workspace root must be an existing directory".to_string());
        }
        let id = format!("workspace-{}", Uuid::new_v4().simple());
        let mut inner = self.lock()?;
        if inner.workspaces.len() >= MAX_WORKSPACES {
            let removable = inner.workspaces.keys().next().cloned();
            if let Some(removable) = removable {
                inner.workspaces.remove(&removable);
            }
        }
        inner
            .workspaces
            .insert(id.clone(), WorkspaceRoot { root: root.clone() });
        Ok(WorkspaceOpenResult {
            workspace_id: id,
            root: path_text(&root),
        })
    }

    /// Closes a workspace registration without deleting any files.
    pub fn close_workspace(&self, workspace_id: &str) -> Result<bool, String> {
        validate_identifier(workspace_id, "workspace_id")?;
        Ok(self.lock()?.workspaces.remove(workspace_id).is_some())
    }

    /// Lists a workspace directory within fixed bounds without following links recursively.
    pub fn list_workspace(
        &self,
        workspace_id: &str,
        relative: &str,
        recursive: bool,
    ) -> Result<Vec<WorkspaceEntry>, String> {
        let root = self.workspace(workspace_id)?;
        let directory = resolve_workspace_path(&root.root, relative, true)?;
        if !directory.is_dir() {
            return Err("Workspace listing target is not a directory".to_string());
        }
        let mut output = Vec::new();
        collect_workspace_entries(&root.root, &directory, recursive, &mut output)?;
        Ok(output)
    }

    /// Reads a bounded UTF-8 workspace file and returns its digest.
    pub fn read_workspace(
        &self,
        workspace_id: &str,
        relative: &str,
        max_bytes: usize,
    ) -> Result<WorkspaceReadResult, String> {
        let root = self.workspace(workspace_id)?;
        let target = resolve_workspace_path(&root.root, relative, true)?;
        if !target.is_file() {
            return Err("Workspace read target is not a file".to_string());
        }
        let max_bytes = max_bytes.clamp(1, MAX_WORKSPACE_READ_BYTES);
        let metadata = fs::metadata(&target)
            .map_err(|err| format!("Failed to read file metadata: {}", err))?;
        if metadata.len() > max_bytes as u64 {
            return Err(format!("File exceeds the {}-byte read limit", max_bytes));
        }
        let bytes =
            fs::read(&target).map_err(|err| format!("Failed to read workspace file: {}", err))?;
        let content = String::from_utf8(bytes.clone())
            .map_err(|_| "Workspace file is not UTF-8 text".to_string())?;
        Ok(WorkspaceReadResult {
            path: relative_text(&root.root, &target)?,
            content,
            bytes: bytes.len(),
            sha256: sha256_hex(&bytes),
        })
    }

    /// Atomically replaces a workspace file through a same-directory temporary file and uses
    /// digests to reject concurrent overwrites.
    pub fn atomic_write_workspace(
        &self,
        workspace_id: &str,
        relative: &str,
        content: String,
        expected_sha256: Option<String>,
    ) -> Result<WorkspaceWriteResult, String> {
        let root = self.workspace(workspace_id)?;
        let target = resolve_workspace_path(&root.root, relative, false)?;
        if target.is_dir() {
            return Err("Atomic write target cannot be a directory".to_string());
        }
        validate_expected_sha256(expected_sha256.as_deref())?;
        let parent = target
            .parent()
            .ok_or_else(|| "Atomic write target has no parent directory".to_string())?;
        if !parent.is_dir() {
            return Err("Parent directory of the atomic write target does not exist".to_string());
        }
        let previous = if target.exists() {
            Some(
                fs::read(&target)
                    .map_err(|err| format!("Failed to read the previous file: {}", err))?,
            )
        } else {
            None
        };
        let previous_sha256 = previous.as_deref().map(sha256_hex);
        if let Some(expected) = expected_sha256.as_deref() {
            if previous_sha256.as_deref() != Some(expected.to_ascii_lowercase().as_str()) {
                return Err(
                    "Atomic write conflict: current SHA-256 does not match expected_sha256"
                        .to_string(),
                );
            }
        }
        let bytes = content.into_bytes();
        let temp = parent.join(format!(
            ".bt-production-{}-{}.tmp",
            std::process::id(),
            Uuid::new_v4().simple()
        ));
        let write_result = (|| -> Result<(), String> {
            let mut file = OpenOptions::new()
                .create_new(true)
                .write(true)
                .open(&temp)
                .map_err(|err| {
                    format!("Failed to create same-directory temporary file: {}", err)
                })?;
            file.write_all(&bytes)
                .map_err(|err| format!("Failed to write temporary file: {}", err))?;
            file.sync_all()
                .map_err(|err| format!("Failed to flush temporary file: {}", err))?;
            if let Some(expected) = expected_sha256.as_deref() {
                let current = fs::read(&target)
                    .map_err(|err| format!("Pre-replacement verification failed: {}", err))?;
                if sha256_hex(&current) != expected.to_ascii_lowercase() {
                    return Err(
                        "Atomic write conflict: file was modified externally during the write"
                            .to_string(),
                    );
                }
            }
            atomic_replace(&temp, &target)
        })();
        if write_result.is_err() {
            let _ = fs::remove_file(&temp);
        }
        write_result?;
        Ok(WorkspaceWriteResult {
            path: relative_text(&root.root, &target)?,
            bytes: bytes.len(),
            sha256: sha256_hex(&bytes),
            previous_sha256,
        })
    }

    /// Starts a bounded native process without a shell.
    pub fn start_process(
        &self,
        window: WebviewWindow,
        options: ProcessStartOptions,
    ) -> Result<ProcessSnapshot, String> {
        validate_process_options(&options)?;
        let root = self.workspace(&options.workspace_id)?;
        let cwd = resolve_workspace_path(&root.root, &options.cwd, true)?;
        if !cwd.is_dir() {
            return Err("Process cwd must be a directory within the workspace".to_string());
        }
        let output_limit = options.output_limit.clamp(1, MAX_PROCESS_OUTPUT_LIMIT);
        let mut command = Command::new(&options.program);
        command
            .args(&options.args)
            .current_dir(&cwd)
            .stdin(Stdio::null())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped());
        for (name, value) in &options.environment {
            command.env(name, value);
        }
        #[cfg(windows)]
        {
            use std::os::windows::process::CommandExt;
            command.creation_flags(0x0800_0000);
        }
        let mut child = command
            .spawn()
            .map_err(|err| format!("Failed to start native process: {}", err))?;
        let pid = child.id();
        let started_at = now_millis();
        let id = format!("process-{}", Uuid::new_v4().simple());
        let identity =
            sha256_hex(format!("{}:{}:{}:{}", id, pid, options.program, started_at).as_bytes());
        let stdout = child.stdout.take();
        let stderr = child.stderr.take();
        let process = Arc::new(ManagedProcess {
            meta: ProcessMeta {
                id: id.clone(),
                task_id: options.task_id.clone(),
                identity,
                pid,
                program: options.program,
                args: options.args,
                cwd: path_text(&cwd),
                started_at,
                output_limit,
            },
            child: Mutex::new(child),
            running: AtomicBool::new(true),
            exit_code: AtomicI32::new(i32::MIN),
            timed_out: AtomicBool::new(false),
            stdout: Mutex::new(Vec::with_capacity(output_limit.min(8192))),
            stderr: Mutex::new(Vec::with_capacity(output_limit.min(8192))),
            stdout_dropped: AtomicUsize::new(0),
            stderr_dropped: AtomicUsize::new(0),
        });
        {
            let mut inner = self.lock()?;
            prune_finished_processes(&mut inner.processes);
            if inner.processes.len() >= MAX_PROCESSES {
                let mut child = process
                    .child
                    .lock()
                    .map_err(|_| "Native process handle lock is poisoned".to_string())?;
                let _ = crate::libs::process::terminate_child_process_tree(&mut child);
                return Err(format!(
                    "Native process registration limit of {} reached",
                    MAX_PROCESSES
                ));
            }
            inner.processes.insert(id.clone(), Arc::clone(&process));
        }
        dispatch_process_event(&window, &process, "start", String::new());
        if let Some(stdout) = stdout {
            spawn_pipe_reader(window.clone(), Arc::clone(&process), stdout, false);
        }
        if let Some(stderr) = stderr {
            spawn_pipe_reader(window.clone(), Arc::clone(&process), stderr, true);
        }
        spawn_process_monitor(window, Arc::clone(&process), options.timeout_ms);
        Ok(process.snapshot())
    }

    /// Queries a native process and verifies its task ownership and identity.
    pub fn process_status(
        &self,
        process_id: &str,
        task_id: &str,
        identity: &str,
    ) -> Result<ProcessSnapshot, String> {
        Ok(self
            .owned_process(process_id, task_id, identity)?
            .snapshot())
    }

    /// Stops one native process tree precisely.
    pub fn stop_process(
        &self,
        window: &WebviewWindow,
        process_id: &str,
        task_id: &str,
        identity: &str,
    ) -> Result<ProcessSnapshot, String> {
        let process = self.owned_process(process_id, task_id, identity)?;
        stop_managed_process(&process, false)?;
        dispatch_process_event(window, &process, "stopped", String::new());
        Ok(process.snapshot())
    }

    /// Stops only process trees registered to the specified task, without affecting other tasks
    /// or external processes.
    pub fn stop_task_processes(
        &self,
        window: &WebviewWindow,
        task_id: &str,
    ) -> Result<Vec<ProcessSnapshot>, String> {
        validate_identifier(task_id, "task_id")?;
        let processes = self
            .lock()?
            .processes
            .values()
            .filter(|process| process.meta.task_id == task_id)
            .cloned()
            .collect::<Vec<_>>();
        let mut stopped = Vec::new();
        for process in processes {
            if process.running.load(Ordering::Acquire) {
                stop_managed_process(&process, false)?;
                dispatch_process_event(window, &process, "stopped", String::new());
            }
            stopped.push(process.snapshot());
        }
        Ok(stopped)
    }

    /// Generates a cleanup preview and secondary confirmation ticket covering only the current
    /// application's own directory.
    pub fn prepare_cleanup(&self, app_name: &str) -> Result<CleanupPreview, String> {
        let app_name = sanitize_app_name(app_name)?;
        let root = app_data_root(&app_name)?;
        let categories = cleanup_categories(&root)?;
        let total_files = categories.iter().map(|item| item.files).sum();
        let total_bytes = categories.iter().map(|item| item.bytes).sum();
        let token = Uuid::new_v4().simple().to_string();
        self.lock()?.cleanup_ticket = Some(CleanupTicket {
            app_name,
            token: token.clone(),
            created_at: Instant::now(),
        });
        Ok(CleanupPreview {
            confirm_token: token,
            categories,
            total_files,
            total_bytes,
            boundary: format!(
                "Only fixed application-owned subdirectories under {} will be cleared; open workspaces will not be accessed or deleted",
                path_text(&root)
            ),
        })
    }

    /// Consumes a one-time ticket and clears fixed application data categories.
    pub fn confirm_cleanup(
        &self,
        app_name: &str,
        confirm_token: &str,
    ) -> Result<CleanupResult, String> {
        let app_name = sanitize_app_name(app_name)?;
        let ticket = self.lock()?.cleanup_ticket.take().ok_or_else(|| {
            "Obtain a data cleanup preview and complete secondary confirmation first".to_string()
        })?;
        if ticket.app_name != app_name
            || ticket.token != confirm_token
            || ticket.created_at.elapsed() > CLEANUP_TICKET_TTL
        {
            return Err("Data cleanup confirmation ticket is invalid or expired".to_string());
        }
        let root = app_data_root(&app_name)?;
        let categories = cleanup_categories(&root)?;
        let removed_files = categories.iter().map(|item| item.files).sum();
        let removed_bytes = categories.iter().map(|item| item.bytes).sum();
        let mut cleared = Vec::new();
        for (name, directory) in cleanup_paths(&root) {
            ensure_direct_child(&root, &directory)?;
            if directory.exists() {
                fs::remove_dir_all(&directory)
                    .map_err(|err| format!("Failed to clear {}: {}", name, err))?;
            }
            cleared.push(name.to_string());
        }
        Ok(CleanupResult {
            cleared,
            removed_files,
            removed_bytes,
            workspace_untouched: true,
        })
    }

    /// Atomically saves bounded JSON state in the application's sessions directory.
    pub fn store_data(&self, app_name: &str, key: &str, value: JsonValue) -> Result<(), String> {
        validate_data_key(key)?;
        let raw = serde_json::to_vec(&value)
            .map_err(|err| format!("Failed to serialize application data: {}", err))?;
        if raw.len() > 4 * 1024 * 1024 {
            return Err("An application data file cannot exceed 4 MiB".to_string());
        }
        let root = app_data_root(&sanitize_app_name(app_name)?)?.join("sessions");
        fs::create_dir_all(&root)
            .map_err(|err| format!("Failed to create sessions directory: {}", err))?;
        atomic_write_bytes(&root.join(format!("{}.json", key)), &raw)
    }

    /// Reads bounded JSON state from the application's sessions directory.
    pub fn load_data(&self, app_name: &str, key: &str) -> Result<Option<JsonValue>, String> {
        validate_data_key(key)?;
        let target = app_data_root(&sanitize_app_name(app_name)?)?
            .join("sessions")
            .join(format!("{}.json", key));
        if !target.is_file() {
            return Ok(None);
        }
        let metadata = fs::metadata(&target)
            .map_err(|err| format!("Failed to read application data: {}", err))?;
        if metadata.len() > 4 * 1024 * 1024 {
            return Err("Application data file exceeds the 4 MiB limit".to_string());
        }
        let raw =
            fs::read(&target).map_err(|err| format!("Failed to read application data: {}", err))?;
        serde_json::from_slice(&raw)
            .map(Some)
            .map_err(|err| format!("Failed to parse application data: {}", err))
    }

    /// Clones a workspace record to avoid holding the global lock during file operations.
    fn workspace(&self, workspace_id: &str) -> Result<WorkspaceRoot, String> {
        validate_identifier(workspace_id, "workspace_id")?;
        self.lock()?
            .workspaces
            .get(workspace_id)
            .cloned()
            .ok_or_else(|| "Workspace registration does not exist or has been closed".to_string())
    }

    /// Retrieves and verifies a native process record.
    fn owned_process(
        &self,
        process_id: &str,
        task_id: &str,
        identity: &str,
    ) -> Result<Arc<ManagedProcess>, String> {
        validate_identifier(process_id, "process_id")?;
        validate_identifier(task_id, "task_id")?;
        if identity.len() != 64 || !identity.bytes().all(|byte| byte.is_ascii_hexdigit()) {
            return Err("Process identity is invalid".to_string());
        }
        let process = self
            .lock()?
            .processes
            .get(process_id)
            .cloned()
            .ok_or_else(|| "Native process record does not exist".to_string())?;
        if process.meta.task_id != task_id || process.meta.identity != identity {
            return Err("Process identity or task ownership does not match".to_string());
        }
        let pid = process
            .child
            .lock()
            .map_err(|_| "Native process handle lock is poisoned".to_string())?
            .id();
        if pid != process.meta.pid {
            return Err("Process PID does not match the registered handle".to_string());
        }
        Ok(process)
    }

    /// Locks internal state and handles poisoned locks consistently.
    fn lock(&self) -> Result<std::sync::MutexGuard<'_, ProductionStateInner>, String> {
        self.inner
            .lock()
            .map_err(|_| "Production desktop API state lock is poisoned".to_string())
    }
}

impl Drop for ProductionState {
    /// Cancels all streams and terminates registered subprocesses on application exit so
    /// background resources do not outlive the application.
    fn drop(&mut self) {
        let Ok(mut inner) = self.inner.lock() else {
            return;
        };
        for (_, control) in inner.streams.drain() {
            let _ = control.cancel.send(true);
        }
        let processes = inner
            .processes
            .drain()
            .map(|(_, process)| process)
            .collect::<Vec<_>>();
        drop(inner);
        for process in processes {
            if process.running.load(Ordering::Acquire) {
                let _ = stop_managed_process(&process, false);
            }
        }
    }
}

impl ManagedProcess {
    /// Builds a safe process snapshot without exposing handles or environment variables.
    fn snapshot(&self) -> ProcessSnapshot {
        let exit_code = self.exit_code.load(Ordering::Acquire);
        ProcessSnapshot {
            id: self.meta.id.clone(),
            task_id: self.meta.task_id.clone(),
            identity: self.meta.identity.clone(),
            pid: self.meta.pid,
            program: self.meta.program.clone(),
            args: self.meta.args.clone(),
            cwd: self.meta.cwd.clone(),
            running: self.running.load(Ordering::Acquire),
            exit_code: (exit_code != i32::MIN).then_some(exit_code),
            timed_out: self.timed_out.load(Ordering::Acquire),
            stdout: self
                .stdout
                .lock()
                .map(|value| String::from_utf8_lossy(&value).into_owned())
                .unwrap_or_default(),
            stderr: self
                .stderr
                .lock()
                .map(|value| String::from_utf8_lossy(&value).into_owned())
                .unwrap_or_default(),
            stdout_dropped: self.stdout_dropped.load(Ordering::Acquire),
            stderr_dropped: self.stderr_dropped.load(Ordering::Acquire),
            started_at: self.meta.started_at,
        }
    }
}

/// Default HTTP method.
fn default_post_method() -> String {
    "POST".to_string()
}

/// Default HTTP timeout.
fn default_http_timeout_ms() -> u64 {
    120_000
}

/// Default streaming response limit.
fn default_stream_bytes() -> usize {
    MAX_STREAM_BYTES
}

/// Default process output limit.
fn default_process_output_limit() -> usize {
    DEFAULT_PROCESS_OUTPUT_LIMIT
}

/// Validates all external streaming request inputs.
fn validate_stream_options(options: &HttpStreamOptions) -> Result<(), String> {
    validate_identifier(&options.request_id, "request_id")?;
    let url = url::Url::parse(options.url.trim())
        .map_err(|_| "Invalid streaming request URL".to_string())?;
    if !matches!(url.scheme(), "http" | "https") || url.host_str().is_none() {
        return Err("Streaming request URL must be an absolute HTTP/HTTPS URL".to_string());
    }
    if options.method.len() > 16
        || !options
            .method
            .bytes()
            .all(|byte| byte.is_ascii_alphabetic())
    {
        return Err("Invalid streaming request method".to_string());
    }
    if options.headers.len() > 32 {
        return Err("Streaming requests cannot have more than 32 headers".to_string());
    }
    for (name, value) in &options.headers {
        if name.len() > 128
            || value.len() > 8_192
            || name.contains(['\r', '\n'])
            || value.contains(['\r', '\n'])
        {
            return Err("Invalid streaming request header name or value".to_string());
        }
        if matches!(
            name.to_ascii_lowercase().as_str(),
            "authorization" | "proxy-authorization" | "cookie"
        ) {
            return Err(
                "Sensitive request headers must be injected by the native secure credential layer"
                    .to_string(),
            );
        }
    }
    if options.body.len() > 4 * 1024 * 1024 {
        return Err("Streaming request body cannot exceed 4 MiB".to_string());
    }
    if !(1_000..=600_000).contains(&options.timeout_ms) {
        return Err("Streaming request timeout_ms must be within 1000..600000".to_string());
    }
    if !options.credential_id.is_empty() {
        validate_identifier(&options.credential_id, "credential_id")?;
    }
    Ok(())
}

/// Runs an asynchronous streaming request.
async fn run_stream_request(
    shared: Arc<Mutex<ProductionStateInner>>,
    window: WebviewWindow,
    app_name: String,
    options: HttpStreamOptions,
    mut cancel_rx: watch::Receiver<bool>,
) {
    let request_id = options.request_id.clone();
    if !emit_stream_event(
        &shared,
        &window,
        &request_id,
        "start",
        0,
        String::new(),
        String::new(),
        0,
    ) {
        return;
    }
    let request = match build_stream_request(&app_name, &options) {
        Ok(request) => request,
        Err(message) => {
            finish_stream(
                &shared,
                &window,
                &request_id,
                "error",
                0,
                String::new(),
                message,
                0,
            );
            return;
        }
    };
    let response = tokio::select! {
        _ = cancel_rx.changed() => return,
        response = request.send() => response,
    };
    let response = match response {
        Ok(response) => response,
        Err(err) => {
            finish_stream(
                &shared,
                &window,
                &request_id,
                "error",
                0,
                String::new(),
                redact_transport_error(&err.to_string()),
                0,
            );
            return;
        }
    };
    let status = response.status().as_u16();
    if !emit_stream_event(
        &shared,
        &window,
        &request_id,
        "headers",
        status,
        String::new(),
        String::new(),
        0,
    ) {
        return;
    }
    let mut received = Vec::with_capacity(16 * 1024);
    let mut chunk_count = 0usize;
    let mut stream = response.bytes_stream();
    loop {
        let next = tokio::select! {
            _ = cancel_rx.changed() => return,
            next = stream.next() => next,
        };
        let Some(next) = next else {
            break;
        };
        let chunk = match next {
            Ok(chunk) => chunk,
            Err(err) => {
                finish_stream(
                    &shared,
                    &window,
                    &request_id,
                    "error",
                    status,
                    String::new(),
                    redact_transport_error(&err.to_string()),
                    received.len(),
                );
                return;
            }
        };
        chunk_count += 1;
        if chunk_count > MAX_STREAM_CHUNKS {
            finish_stream(
                &shared,
                &window,
                &request_id,
                "error",
                status,
                String::new(),
                format!(
                    "Streaming response exceeds the {}-chunk limit",
                    MAX_STREAM_CHUNKS
                ),
                received.len(),
            );
            return;
        }
        if received.len().saturating_add(chunk.len()) > options.max_response_bytes {
            finish_stream(
                &shared,
                &window,
                &request_id,
                "error",
                status,
                String::new(),
                format!(
                    "Streaming response exceeds the {}-byte limit",
                    options.max_response_bytes
                ),
                received.len(),
            );
            return;
        }
        received.extend_from_slice(&chunk);
        let text = String::from_utf8_lossy(&chunk).into_owned();
        if !emit_stream_event(
            &shared,
            &window,
            &request_id,
            "chunk",
            status,
            text,
            String::new(),
            received.len(),
        ) {
            return;
        }
    }
    let body = String::from_utf8_lossy(&received).into_owned();
    finish_stream(
        &shared,
        &window,
        &request_id,
        "done",
        status,
        body,
        String::new(),
        received.len(),
    );
}

/// Builds a reqwest request and briefly reads credentials from the current application's
/// plaintext JSON file.
fn build_stream_request(
    app_name: &str,
    options: &HttpStreamOptions,
) -> Result<reqwest::RequestBuilder, String> {
    let method = reqwest::Method::from_bytes(options.method.as_bytes())
        .map_err(|_| "Invalid streaming request method".to_string())?;
    // `rustls-no-provider` does not select a crypto backend on the first HTTPS request. Install
    // ring idempotently before constructing any Client so a knowledge-cache hit cannot skip the
    // standard HTTP initialization and trigger a process-wide panic.
    crate::io::ensure_rustls_provider();
    let client = reqwest::Client::builder()
        .build()
        .map_err(|err| format!("Failed to create streaming HTTP client: {}", err))?;
    let mut request = client
        .request(method, options.url.trim())
        .timeout(Duration::from_millis(options.timeout_ms));
    for (name, value) in &options.headers {
        request = request.header(name, value);
    }
    if !options.credential_id.is_empty() {
        let mut secret = load_credential_bytes(app_name, &options.credential_id)?;
        let mut header = Vec::with_capacity(7 + secret.len());
        header.extend_from_slice(b"Bearer ");
        header.extend_from_slice(&secret);
        let header_value = reqwest::header::HeaderValue::from_bytes(&header).map_err(|_| {
            "Secure credential cannot be used to construct an Authorization header".to_string()
        });
        secret.fill(0);
        header.fill(0);
        request = request.header(reqwest::header::AUTHORIZATION, header_value?);
    }
    if !options.body.is_empty() {
        request = request.body(options.body.clone());
    }
    Ok(request)
}

/// Dispatches a strictly ordered event while the request remains registered.
fn emit_stream_event(
    shared: &Arc<Mutex<ProductionStateInner>>,
    window: &WebviewWindow,
    request_id: &str,
    kind: &str,
    status: u16,
    data: String,
    message: String,
    received_bytes: usize,
) -> bool {
    let Ok(mut inner) = shared.lock() else {
        return false;
    };
    let Some(control) = inner.streams.get_mut(request_id) else {
        return false;
    };
    control.sequence += 1;
    dispatch_dom_event(
        window,
        HTTP_STREAM_EVENT,
        &HttpStreamPayload {
            request_id: request_id.to_string(),
            sequence: control.sequence,
            kind: kind.to_string(),
            status,
            data,
            message,
            received_bytes,
        },
    );
    true
}

/// Dispatches the final event and atomically closes the event gate.
fn finish_stream(
    shared: &Arc<Mutex<ProductionStateInner>>,
    window: &WebviewWindow,
    request_id: &str,
    kind: &str,
    status: u16,
    data: String,
    message: String,
    received_bytes: usize,
) {
    let Ok(mut inner) = shared.lock() else {
        return;
    };
    let Some(control) = inner.streams.remove(request_id) else {
        return;
    };
    dispatch_dom_event(
        window,
        HTTP_STREAM_EVENT,
        &HttpStreamPayload {
            request_id: request_id.to_string(),
            sequence: control.sequence + 1,
            kind: kind.to_string(),
            status,
            data,
            message,
            received_bytes,
        },
    );
}

/// Reduces an underlying network error to text without URL queries or authentication details.
fn redact_transport_error(message: &str) -> String {
    let first = message
        .lines()
        .next()
        .unwrap_or("Streaming HTTP request failed");
    first.chars().take(500).collect()
}

/// Atomically saves application credentials as readable plaintext JSON in the user directory.
pub fn store_credential(app_name: &str, credential_id: &str, secret: String) -> Result<(), String> {
    validate_identifier(credential_id, "credential_id")?;
    if secret.is_empty() || secret.len() > 4096 {
        return Err("Secure credential cannot be empty or exceed 4096 characters".to_string());
    }
    let app_name = sanitize_app_name(app_name)?;
    let target = credential_path(&app_name, credential_id)?;
    let value = CredentialFile {
        schema: 1,
        credential_id: credential_id.to_string(),
        api_key: secret,
    };
    let mut raw = serde_json::to_vec_pretty(&value)
        .map_err(|err| format!("Failed to serialize application credential: {}", err))?;
    let parent = target
        .parent()
        .ok_or_else(|| "Secure credential directory is invalid".to_string())?;
    fs::create_dir_all(parent)
        .map_err(|err| format!("Failed to create secure credential directory: {}", err))?;
    let result = atomic_write_bytes(&target, &raw);
    raw.fill(0);
    result
}

/// Checks whether application credential JSON exists without returning its contents to the page.
pub fn has_credential(app_name: &str, credential_id: &str) -> Result<bool, String> {
    validate_identifier(credential_id, "credential_id")?;
    let app_name = sanitize_app_name(app_name)?;
    if !credential_path(&app_name, credential_id)?.is_file() {
        return Ok(false);
    }
    let mut value = load_credential_bytes(&app_name, credential_id)?;
    value.fill(0);
    Ok(true)
}

/// Deletes one application credential JSON file.
pub fn delete_credential(app_name: &str, credential_id: &str) -> Result<bool, String> {
    validate_identifier(credential_id, "credential_id")?;
    let target = credential_path(&sanitize_app_name(app_name)?, credential_id)?;
    if !target.exists() {
        return Ok(false);
    }
    fs::remove_file(&target)
        .map_err(|err| format!("Failed to delete secure credential: {}", err))?;
    Ok(true)
}

/// Reads credentials from plaintext JSON into a short-lived byte array that the caller must
/// overwrite after use.
fn load_credential_bytes(app_name: &str, credential_id: &str) -> Result<Vec<u8>, String> {
    let target = credential_path(app_name, credential_id)?;
    let mut raw = fs::read(&target)
        .map_err(|_| "Application credential does not exist or cannot be read".to_string())?;
    if raw.len() > 16 * 1024 {
        raw.fill(0);
        return Err("Application credential JSON exceeds the 16 KiB limit".to_string());
    }
    let parsed = serde_json::from_slice(&raw);
    raw.fill(0);
    let value: CredentialFile =
        parsed.map_err(|_| "Invalid application credential JSON format".to_string())?;
    if value.schema != 1 || value.credential_id != credential_id {
        return Err("Application credential JSON identifier does not match".to_string());
    }
    let mut plain = value.api_key.into_bytes();
    if plain.is_empty() || plain.len() > 4096 {
        plain.fill(0);
        return Err("Secure credential content is invalid".to_string());
    }
    Ok(plain)
}

/// Recursively collects workspace entries without following symbolic links or junctions.
fn collect_workspace_entries(
    root: &Path,
    directory: &Path,
    recursive: bool,
    output: &mut Vec<WorkspaceEntry>,
) -> Result<(), String> {
    for entry in fs::read_dir(directory)
        .map_err(|err| format!("Failed to read workspace directory: {}", err))?
    {
        if output.len() >= MAX_WORKSPACE_ENTRIES {
            return Err(format!(
                "Workspace listing exceeds the {}-entry limit",
                MAX_WORKSPACE_ENTRIES
            ));
        }
        let entry =
            entry.map_err(|err| format!("Failed to read workspace directory entry: {}", err))?;
        let metadata = fs::symlink_metadata(entry.path())
            .map_err(|err| format!("Failed to read workspace directory entry metadata: {}", err))?;
        let file_type = metadata.file_type();
        let kind = if file_type.is_symlink() {
            "symlink"
        } else if metadata.is_dir() {
            "directory"
        } else {
            "file"
        };
        output.push(WorkspaceEntry {
            path: relative_text(root, &entry.path())?,
            kind: kind.to_string(),
            bytes: if metadata.is_file() {
                metadata.len()
            } else {
                0
            },
        });
        if recursive && metadata.is_dir() && !file_type.is_symlink() {
            collect_workspace_entries(root, &entry.path(), true, output)?;
        }
    }
    Ok(())
}

/// Resolves a workspace-relative path; for a missing target, uses the deepest existing ancestor
/// to check the canonical path boundary.
fn resolve_workspace_path(
    root: &Path,
    relative: &str,
    must_exist: bool,
) -> Result<PathBuf, String> {
    let relative = Path::new(relative.trim());
    if relative.is_absolute()
        || relative.components().any(|component| {
            matches!(
                component,
                Component::ParentDir | Component::Prefix(_) | Component::RootDir
            )
        })
    {
        return Err("Workspace path must be a relative path without `..`".to_string());
    }
    let candidate = root.join(relative);
    if candidate.exists() {
        let real = fs::canonicalize(&candidate)
            .map_err(|err| format!("Failed to resolve workspace target: {}", err))?;
        ensure_within(root, &real)?;
        return Ok(real);
    }
    if must_exist {
        return Err("Workspace target does not exist".to_string());
    }
    let mut ancestor = candidate.as_path();
    while !ancestor.exists() {
        ancestor = ancestor
            .parent()
            .ok_or_else(|| "Workspace path has no existing ancestor".to_string())?;
    }
    let real_ancestor = fs::canonicalize(ancestor)
        .map_err(|err| format!("Failed to resolve workspace ancestor: {}", err))?;
    ensure_within(root, &real_ancestor)?;
    Ok(candidate)
}

/// Verifies that a canonical path lies within the canonical workspace root.
fn ensure_within(root: &Path, target: &Path) -> Result<(), String> {
    if target == root || target.starts_with(root) {
        Ok(())
    } else {
        Err("Workspace path escapes its boundary".to_string())
    }
}

/// Produces a relative path using forward slashes.
fn relative_text(root: &Path, target: &Path) -> Result<String, String> {
    target
        .strip_prefix(root)
        .map(|value| path_text(value))
        .map_err(|_| "Target path is outside the workspace".to_string())
}

/// Validates native process options and bounded arrays.
fn validate_process_options(options: &ProcessStartOptions) -> Result<(), String> {
    validate_identifier(&options.task_id, "task_id")?;
    validate_identifier(&options.workspace_id, "workspace_id")?;
    if options.program.trim().is_empty() || options.program.len() > 32_768 {
        return Err(
            "Native process program cannot be empty or exceed 32768 characters".to_string(),
        );
    }
    if options.args.len() > 256 || options.args.iter().any(|value| value.len() > 32_768) {
        return Err("Native process args may contain at most 256 items, each no longer than 32768 characters".to_string());
    }
    if options.environment.len() > 64
        || options.environment.iter().any(|(name, value)| {
            name.is_empty() || name.contains('=') || name.len() > 256 || value.len() > 32_768
        })
    {
        return Err("Native process environment is invalid or exceeds its limit".to_string());
    }
    if options.timeout_ms > 24 * 60 * 60 * 1000 {
        return Err("Native process timeout_ms cannot exceed 24 hours".to_string());
    }
    Ok(())
}

/// Starts an output reader thread that retains a bounded tail.
fn spawn_pipe_reader<R: Read + Send + 'static>(
    window: WebviewWindow,
    process: Arc<ManagedProcess>,
    mut reader: R,
    stderr: bool,
) {
    thread::spawn(move || {
        let mut buffer = [0_u8; 8_192];
        loop {
            let count = match reader.read(&mut buffer) {
                Ok(0) | Err(_) => break,
                Ok(count) => count,
            };
            let target = if stderr {
                &process.stderr
            } else {
                &process.stdout
            };
            let dropped = if stderr {
                &process.stderr_dropped
            } else {
                &process.stdout_dropped
            };
            if let Ok(mut output) = target.lock() {
                append_bounded(
                    &mut output,
                    &buffer[..count],
                    process.meta.output_limit,
                    dropped,
                );
            }
            dispatch_process_event(
                &window,
                &process,
                if stderr { "stderr" } else { "stdout" },
                String::from_utf8_lossy(&buffer[..count]).into_owned(),
            );
        }
    });
}

/// Monitors process exit and timeout without blocking the Tauri command.
fn spawn_process_monitor(window: WebviewWindow, process: Arc<ManagedProcess>, timeout_ms: u64) {
    thread::spawn(move || loop {
        let elapsed = now_millis().saturating_sub(process.meta.started_at);
        if timeout_ms > 0
            && elapsed >= timeout_ms as u128
            && process.running.load(Ordering::Acquire)
        {
            process.timed_out.store(true, Ordering::Release);
            let _ = stop_managed_process(&process, true);
            dispatch_process_event(&window, &process, "timeout", String::new());
            break;
        }
        let status = process
            .child
            .lock()
            .ok()
            .and_then(|mut child| child.try_wait().ok().flatten());
        if let Some(status) = status {
            process
                .exit_code
                .store(status.code().unwrap_or(-1), Ordering::Release);
            process.running.store(false, Ordering::Release);
            dispatch_process_event(&window, &process, "exit", String::new());
            break;
        }
        if !process.running.load(Ordering::Acquire) {
            break;
        }
        thread::sleep(Duration::from_millis(25));
    });
}

/// Terminates a native subprocess tree and waits for its handle to finish.
fn stop_managed_process(process: &ManagedProcess, timed_out: bool) -> Result<(), String> {
    if !process.running.swap(false, Ordering::AcqRel) {
        return Ok(());
    }
    if timed_out {
        process.timed_out.store(true, Ordering::Release);
    }
    let mut child = process
        .child
        .lock()
        .map_err(|_| "Native process handle lock is poisoned".to_string())?;
    if child.id() != process.meta.pid {
        return Err(
            "Process PID does not match the registered handle; termination refused".to_string(),
        );
    }
    if child
        .try_wait()
        .map_err(|err| format!("Failed to query process status: {}", err))?
        .is_none()
    {
        crate::libs::process::terminate_child_process_tree(&mut child)?;
    }
    let status = child
        .wait()
        .map_err(|err| format!("Failed to wait for process exit: {}", err))?;
    process
        .exit_code
        .store(status.code().unwrap_or(-1), Ordering::Release);
    Ok(())
}

/// Appends bytes to a tail-bounded buffer.
fn append_bounded(output: &mut Vec<u8>, bytes: &[u8], limit: usize, dropped: &AtomicUsize) {
    if bytes.len() >= limit {
        dropped.fetch_add(output.len() + bytes.len() - limit, Ordering::Relaxed);
        output.clear();
        output.extend_from_slice(&bytes[bytes.len() - limit..]);
        return;
    }
    let overflow = output
        .len()
        .saturating_add(bytes.len())
        .saturating_sub(limit);
    if overflow > 0 {
        output.drain(..overflow);
        dropped.fetch_add(overflow, Ordering::Relaxed);
    }
    output.extend_from_slice(bytes);
}

/// Evicts the oldest finished native process records.
fn prune_finished_processes(processes: &mut HashMap<String, Arc<ManagedProcess>>) {
    while processes.len() >= MAX_PROCESSES {
        let oldest = processes
            .values()
            .filter(|process| !process.running.load(Ordering::Acquire))
            .min_by_key(|process| process.meta.started_at)
            .map(|process| process.meta.id.clone());
        let Some(oldest) = oldest else {
            break;
        };
        processes.remove(&oldest);
    }
}

/// Dispatches a native process event.
fn dispatch_process_event(
    window: &WebviewWindow,
    process: &ManagedProcess,
    kind: &str,
    data: String,
) {
    dispatch_dom_event(
        window,
        PROCESS_EVENT,
        &ProcessEventPayload {
            process_id: process.meta.id.clone(),
            task_id: process.meta.task_id.clone(),
            kind: kind.to_string(),
            data,
            pid: process.meta.pid,
        },
    );
}

/// Dispatches a backend call status event without the BT response body.
pub fn dispatch_backend_event(window: &WebviewWindow, name: &str, ok: bool) {
    #[derive(Serialize)]
    struct BackendPayload<'a> {
        /// BT global function name.
        name: &'a str,
        /// Whether this IPC call succeeded.
        ok: bool,
        /// Backend completion timestamp.
        at: u128,
    }
    dispatch_dom_event(
        window,
        BACKEND_EVENT,
        &BackendPayload {
            name,
            ok,
            at: now_millis(),
        },
    );
}

/// Dispatches a DOM CustomEvent using safe JSON serialization.
fn dispatch_dom_event(window: &WebviewWindow, event: &str, payload: &impl Serialize) {
    let Ok(event) = serde_json::to_string(event) else {
        return;
    };
    let Ok(payload) = serde_json::to_string(payload) else {
        return;
    };
    let _ = window.eval(format!(
        "window.dispatchEvent(new CustomEvent({}, {{ detail: {} }}));",
        event, payload
    ));
}

/// Returns the application's own data root.
fn app_data_root(app_name: &str) -> Result<PathBuf, String> {
    // Automated acceptance tests can isolate only application data, avoiding input-method and
    // WebView configuration in the test directory when USERPROFILE is replaced.
    let base = std::env::var_os("BT_APP_DATA_HOME")
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
        .or_else(|| {
            std::env::var_os("USERPROFILE")
                .filter(|value| !value.is_empty())
                .map(PathBuf::from)
        })
        .or_else(|| {
            std::env::var_os("HOME")
                .filter(|value| !value.is_empty())
                .map(PathBuf::from)
        })
        .ok_or_else(|| {
            "USERPROFILE/HOME is unavailable; cannot determine application data directory"
                .to_string()
        })?;
    Ok(base.join(format!(".{}", app_name.trim_start_matches('.'))))
}

/// Returns a recognizable plaintext JSON credential path.
fn credential_path(app_name: &str, credential_id: &str) -> Result<PathBuf, String> {
    validate_identifier(credential_id, "credential_id")?;
    Ok(app_data_root(app_name)?
        .join("credentials")
        .join(format!("{}.json", credential_id)))
}

/// Returns paths for the fixed cleanup categories.
fn cleanup_paths(root: &Path) -> Vec<(&'static str, PathBuf)> {
    vec![
        ("knowledge_cache", root.join("knowledge-cache")),
        ("sessions", root.join("sessions")),
        ("logs", root.join("logs")),
        ("temp", root.join("temp")),
        ("credentials", root.join("credentials")),
    ]
}

/// Calculates usage for all fixed cleanup categories.
fn cleanup_categories(root: &Path) -> Result<Vec<CleanupCategory>, String> {
    cleanup_paths(root)
        .into_iter()
        .map(|(name, path)| {
            ensure_direct_child(root, &path)?;
            let (files, bytes) = directory_usage(&path)?;
            Ok(CleanupCategory {
                name: name.to_string(),
                files,
                bytes,
            })
        })
        .collect()
}

/// Counts directory files and bytes without following links.
fn directory_usage(path: &Path) -> Result<(usize, u64), String> {
    if !path.exists() {
        return Ok((0, 0));
    }
    let metadata = fs::symlink_metadata(path)
        .map_err(|err| format!("Failed to read cleanup directory: {}", err))?;
    if metadata.file_type().is_symlink() {
        return Err(
            "Application data cleanup directory cannot be a symbolic link or junction".to_string(),
        );
    }
    if metadata.is_file() {
        return Ok((1, metadata.len()));
    }
    let mut files = 0usize;
    let mut bytes = 0u64;
    for entry in
        fs::read_dir(path).map_err(|err| format!("Failed to read cleanup directory: {}", err))?
    {
        let entry =
            entry.map_err(|err| format!("Failed to read cleanup directory entry: {}", err))?;
        let metadata = fs::symlink_metadata(entry.path())
            .map_err(|err| format!("Failed to read cleanup directory entry: {}", err))?;
        if metadata.file_type().is_symlink() {
            return Err(
                "Application data cleanup tree cannot contain symbolic links or junctions"
                    .to_string(),
            );
        }
        if metadata.is_dir() {
            let child = directory_usage(&entry.path())?;
            files = files.saturating_add(child.0);
            bytes = bytes.saturating_add(child.1);
        } else {
            files = files.saturating_add(1);
            bytes = bytes.saturating_add(metadata.len());
        }
    }
    Ok((files, bytes))
}

/// Ensures the cleanup target is a direct child of the data root.
fn ensure_direct_child(root: &Path, target: &Path) -> Result<(), String> {
    if target.parent() == Some(root) && target != root {
        Ok(())
    } else {
        Err("Data cleanup target crosses the application-owned directory boundary".to_string())
    }
}

/// Validates that an application name contains only safe filename characters.
fn sanitize_app_name(app_name: &str) -> Result<String, String> {
    let value = app_name.trim();
    if value.is_empty()
        || value.len() > 80
        || !value
            .bytes()
            .any(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'))
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-' | b'.'))
    {
        return Err("Application name is not valid for a secure data directory".to_string());
    }
    Ok(value.to_string())
}

/// Validates a short-lived ID.
fn validate_identifier(value: &str, name: &str) -> Result<(), String> {
    if value.is_empty()
        || value.len() > 128
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-' | b'.'))
    {
        Err(format!("Invalid {} format", name))
    } else {
        Ok(())
    }
}

/// Validates a bounded application data key.
fn validate_data_key(value: &str) -> Result<(), String> {
    if value.is_empty()
        || value.len() > 64
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'))
    {
        Err("Invalid application data key format".to_string())
    } else {
        Ok(())
    }
}

/// Validates an optional SHA-256.
fn validate_expected_sha256(value: Option<&str>) -> Result<(), String> {
    if let Some(value) = value {
        if value.len() != 64 || !value.bytes().all(|byte| byte.is_ascii_hexdigit()) {
            return Err("expected_sha256 must be 64 hexadecimal characters".to_string());
        }
    }
    Ok(())
}

/// Computes a lowercase hexadecimal SHA-256 digest.
fn sha256_hex(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

/// Returns the current Unix timestamp in milliseconds.
fn now_millis() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
}

/// Formats paths consistently with forward slashes.
fn path_text(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

/// Atomically writes an application-private file.
fn atomic_write_bytes(target: &Path, bytes: &[u8]) -> Result<(), String> {
    let parent = target
        .parent()
        .ok_or_else(|| "Atomic write target has no parent directory".to_string())?;
    fs::create_dir_all(parent)
        .map_err(|err| format!("Failed to create atomic write directory: {}", err))?;
    let temp = parent.join(format!(
        ".bt-production-{}-{}.tmp",
        std::process::id(),
        Uuid::new_v4().simple()
    ));
    let result = (|| -> Result<(), String> {
        let mut file = File::create(&temp)
            .map_err(|err| format!("Failed to create temporary file: {}", err))?;
        file.write_all(bytes)
            .map_err(|err| format!("Failed to write temporary file: {}", err))?;
        file.sync_all()
            .map_err(|err| format!("Failed to flush temporary file: {}", err))?;
        atomic_replace(&temp, target)
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temp);
    }
    result
}

/// Uses MoveFileExW for an atomic same-volume replacement on Windows.
#[cfg(windows)]
fn atomic_replace(from: &Path, to: &Path) -> Result<(), String> {
    use std::os::windows::ffi::OsStrExt;
    use windows_sys::Win32::Storage::FileSystem::{
        MoveFileExW, MOVEFILE_REPLACE_EXISTING, MOVEFILE_WRITE_THROUGH,
    };
    let from_wide = from
        .as_os_str()
        .encode_wide()
        .chain(Some(0))
        .collect::<Vec<_>>();
    let to_wide = to
        .as_os_str()
        .encode_wide()
        .chain(Some(0))
        .collect::<Vec<_>>();
    if unsafe {
        MoveFileExW(
            from_wide.as_ptr(),
            to_wide.as_ptr(),
            MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH,
        )
    } == 0
    {
        return Err(format!(
            "Atomic replacement failed: {}",
            std::io::Error::last_os_error()
        ));
    }
    Ok(())
}

/// Uses rename for an atomic same-filesystem replacement outside Windows.
#[cfg(not(windows))]
fn atomic_replace(from: &Path, to: &Path) -> Result<(), String> {
    fs::rename(from, to).map_err(|err| format!("Atomic replacement failed: {}", err))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Relative path resolution must reject parent-directory and link escapes.
    #[test]
    fn workspace_resolution_rejects_parent_escape() {
        let root = std::env::temp_dir().join(format!("bt-production-workspace-{}", Uuid::new_v4()));
        fs::create_dir_all(&root).unwrap();
        let real = fs::canonicalize(&root).unwrap();
        assert!(resolve_workspace_path(&real, "../outside", false).is_err());
        let _ = fs::remove_dir_all(root);
    }

    /// Bounded output must retain only the tail and count discarded bytes.
    #[test]
    fn bounded_output_keeps_tail() {
        let mut output = b"1234".to_vec();
        let dropped = AtomicUsize::new(0);
        append_bounded(&mut output, b"56789", 6, &dropped);
        assert_eq!(output, b"456789");
        assert_eq!(dropped.load(Ordering::Relaxed), 3);
    }

    /// Cleanup targets must be direct children of the fixed data root.
    #[test]
    fn cleanup_boundary_rejects_nested_or_root_target() {
        let root = PathBuf::from("C:/safe/desktop_app");
        assert!(ensure_direct_child(&root, &root.join("sessions")).is_ok());
        assert!(ensure_direct_child(&root, &root).is_err());
        assert!(ensure_direct_child(&root, &root.join("sessions/nested")).is_err());
    }

    /// Plaintext credential JSON must contain explicit schema, original ID, and API key fields.
    #[test]
    fn credential_json_round_trip_keeps_schema_and_identifier() {
        let raw = serde_json::to_vec(&CredentialFile {
            schema: 1,
            credential_id: "profile-1".to_string(),
            api_key: "test-only-secret".to_string(),
        })
        .unwrap();
        let parsed: CredentialFile = serde_json::from_slice(&raw).unwrap();
        assert_eq!(parsed.schema, 1);
        assert_eq!(parsed.credential_id, "profile-1");
        assert_eq!(parsed.api_key.len(), 16);
    }

    /// Credential paths use a hidden application root and recognizable JSON filenames instead of
    /// DPAPI-hashed filenames.
    #[test]
    fn credential_path_uses_hidden_app_root_and_json_name() {
        let target = credential_path("demo_app", "profile-1").unwrap();
        assert!(target.ends_with(Path::new(".demo_app/credentials/profile-1.json")));
        assert!(sanitize_app_name(".").is_err());
        assert!(sanitize_app_name("...").is_err());
    }

    /// A fresh process must install the rustls provider before directly creating its first
    /// production HTTP client.
    #[test]
    fn stream_client_installs_rustls_provider_in_cold_process() {
        const CHILD_FLAG: &str = "BT_TEST_RUSTLS_COLD_PROCESS";
        if std::env::var_os(CHILD_FLAG).is_some() {
            let options = HttpStreamOptions {
                request_id: "cold-provider".to_string(),
                url: "http://127.0.0.1:1".to_string(),
                method: "GET".to_string(),
                headers: HashMap::new(),
                body: String::new(),
                credential_id: String::new(),
                timeout_ms: 1_000,
                max_response_bytes: 1024,
            };
            assert!(build_stream_request("cold_test", &options).is_ok());
            return;
        }

        let output = std::process::Command::new(std::env::current_exe().unwrap())
            .args([
                "--exact",
                "app::api::production::tests::stream_client_installs_rustls_provider_in_cold_process",
                "--nocapture",
            ])
            .env(CHILD_FLAG, "1")
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "Cold-start HTTP client subprocess failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
