//! Global shortcut desktop API implementation for `bt.shortcut`.

use serde::Serialize;
#[cfg(not(target_os = "linux"))]
use std::collections::HashMap;
#[cfg(not(target_os = "linux"))]
use std::sync::{Mutex, MutexGuard};
use tauri::AppHandle;
#[cfg(not(target_os = "linux"))]
use tauri::{Emitter, Manager};
#[cfg(not(target_os = "linux"))]
use tauri_plugin_global_shortcut::{
    GlobalShortcutExt, Shortcut, ShortcutEvent, ShortcutState as NativeShortcutState,
};

/// Global shortcut triggered event name.
pub const SHORTCUT_TRIGGERED_EVENT: &str = "bt://shortcut/triggered";

/// Maximum number of global shortcuts registered concurrently by one desktop application.
pub(super) const MAX_SHORTCUTS: usize = 16;

/// Shared runtime state for global shortcuts.
#[cfg(not(target_os = "linux"))]
pub struct ShortcutState {
    /// Bidirectional index between stable caller IDs and native shortcut IDs.
    inner: Mutex<ShortcutStateInner>,
}

/// Contents of the shared global shortcut runtime state.
#[cfg(not(target_os = "linux"))]
struct ShortcutStateInner {
    /// Index from stable caller IDs to shortcut records.
    by_id: HashMap<String, RegisteredShortcut>,
    /// Index from native shortcut IDs to stable caller IDs.
    by_native_id: HashMap<u32, String>,
}

/// Record for one registered global shortcut.
#[cfg(not(target_os = "linux"))]
#[derive(Clone, Debug)]
struct RegisteredShortcut {
    /// Caller-provided shortcut text with surrounding whitespace removed.
    accelerator: String,
    /// Stable native shortcut ID generated by `global-hotkey`.
    native_id: u32,
}

/// Global shortcut event payload dispatched to the main window.
#[derive(Clone, Debug, Serialize)]
pub struct ShortcutTriggeredEvent {
    /// Stable shortcut ID provided when the page registered it.
    pub shortcut_id: String,
    /// Successfully registered shortcut combination text.
    pub accelerator: String,
}

#[cfg(not(target_os = "linux"))]
impl ShortcutState {
    /// Creates empty global shortcut state.
    pub fn new() -> Self {
        Self {
            inner: Mutex::new(ShortcutStateInner {
                by_id: HashMap::with_capacity(4),
                by_native_id: HashMap::with_capacity(4),
            }),
        }
    }

    /// Returns the page event payload for a native shortcut ID.
    fn event_for_native_id(
        &self,
        native_id: u32,
    ) -> Result<Option<ShortcutTriggeredEvent>, String> {
        let inner = self.lock()?;
        let Some(shortcut_id) = inner.by_native_id.get(&native_id) else {
            return Ok(None);
        };
        let Some(shortcut) = inner.by_id.get(shortcut_id) else {
            return Ok(None);
        };
        Ok(Some(ShortcutTriggeredEvent {
            shortcut_id: shortcut_id.clone(),
            accelerator: shortcut.accelerator.clone(),
        }))
    }

    /// Locks shortcut state and converts a poisoned lock into an error.
    fn lock(&self) -> Result<MutexGuard<'_, ShortcutStateInner>, String> {
        self.inner
            .lock()
            .map_err(|_| "Global shortcut state is corrupted".to_string())
    }
}

/// Registers or atomically replaces a global shortcut.
#[cfg(not(target_os = "linux"))]
pub fn register(
    app: AppHandle,
    state: &ShortcutState,
    shortcut_id: String,
    accelerator: String,
) -> Result<(), String> {
    let shortcut_id = validate_shortcut_id(shortcut_id)?;
    let accelerator = accelerator.trim().to_string();
    if accelerator.is_empty() || accelerator.len() > 128 {
        return Err("Accelerator cannot be empty or exceed 128 characters".to_string());
    }
    let shortcut: Shortcut = accelerator
        .parse()
        .map_err(|err| format!("Invalid shortcut format: {}", err))?;
    let native_id = shortcut.id();
    let global_shortcut = app.global_shortcut();
    let mut inner = state.lock()?;

    if let Some(existing) = inner.by_id.get(&shortcut_id) {
        if existing.native_id == native_id {
            return Ok(());
        }
    } else if inner.by_id.len() >= MAX_SHORTCUTS {
        return Err(format!(
            "Global shortcut count cannot exceed {}",
            MAX_SHORTCUTS
        ));
    }

    if let Some(existing_id) = inner.by_native_id.get(&native_id) {
        if existing_id != &shortcut_id {
            return Err(format!(
                "Shortcut is already registered by `{}`",
                existing_id
            ));
        }
    }

    let previous = inner.by_id.get(&shortcut_id).cloned();
    if let Some(previous) = previous.as_ref() {
        global_shortcut
            .unregister(previous.accelerator.as_str())
            .map_err(|err| format!("Failed to unregister previous shortcut: {}", err))?;
    }

    if let Err(err) = global_shortcut.register(shortcut) {
        if let Some(previous) = previous.as_ref() {
            if let Err(rollback_err) = global_shortcut.register(previous.accelerator.as_str()) {
                inner.by_id.remove(&shortcut_id);
                inner.by_native_id.remove(&previous.native_id);
                return Err(format!(
                    "Failed to register global shortcut: {}; also failed to restore previous shortcut: {}",
                    err, rollback_err
                ));
            }
        }
        return Err(format!("Failed to register global shortcut: {}", err));
    }

    if let Some(previous) = previous {
        inner.by_native_id.remove(&previous.native_id);
    }
    inner.by_native_id.insert(native_id, shortcut_id.clone());
    inner.by_id.insert(
        shortcut_id,
        RegisteredShortcut {
            accelerator,
            native_id,
        },
    );
    Ok(())
}

/// Unregisters the global shortcut associated with a stable ID.
#[cfg(not(target_os = "linux"))]
pub fn unregister(
    app: AppHandle,
    state: &ShortcutState,
    shortcut_id: String,
) -> Result<bool, String> {
    let shortcut_id = validate_shortcut_id(shortcut_id)?;
    let mut inner = state.lock()?;
    let Some(shortcut) = inner.by_id.get(&shortcut_id).cloned() else {
        return Ok(false);
    };
    app.global_shortcut()
        .unregister(shortcut.accelerator.as_str())
        .map_err(|err| format!("Failed to unregister global shortcut: {}", err))?;
    inner.by_id.remove(&shortcut_id);
    inner.by_native_id.remove(&shortcut.native_id);
    Ok(true)
}

/// Unregisters all global shortcuts registered by the current application through the BT bridge.
#[cfg(not(target_os = "linux"))]
pub fn unregister_all(app: AppHandle, state: &ShortcutState) -> Result<(), String> {
    let mut inner = state.lock()?;
    if inner.by_id.is_empty() {
        return Ok(());
    }
    let shortcuts = inner
        .by_id
        .values()
        .map(|shortcut| {
            shortcut
                .accelerator
                .parse::<Shortcut>()
                .map_err(|err| format!("Registered shortcut state is invalid: {}", err))
        })
        .collect::<Result<Vec<_>, _>>()?;
    app.global_shortcut()
        .unregister_multiple(shortcuts)
        .map_err(|err| format!("Failed to unregister all global shortcuts: {}", err))?;
    inner.by_id.clear();
    inner.by_native_id.clear();
    Ok(())
}

/// Receives native shortcut events and dispatches only key presses to the main window.
#[cfg(not(target_os = "linux"))]
pub fn dispatch(app: &AppHandle, shortcut: &Shortcut, event: ShortcutEvent) {
    if event.state != NativeShortcutState::Pressed {
        return;
    }
    let Some(state) = app.try_state::<ShortcutState>() else {
        return;
    };
    let Ok(Some(payload)) = state.event_for_native_id(shortcut.id()) else {
        return;
    };
    let _ = app.emit_to("main", SHORTCUT_TRIGGERED_EVENT, payload);
}

/// Validates caller shortcut IDs to keep empty, unbounded, or unpredictable text out of persistent state.
pub(super) fn validate_shortcut_id(shortcut_id: String) -> Result<String, String> {
    let shortcut_id = shortcut_id.trim().to_string();
    if shortcut_id.is_empty()
        || shortcut_id.len() > 64
        || !shortcut_id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
    {
        return Err("shortcut_id must be 1-64 characters and contain only letters, digits, hyphens, and underscores".to_string());
    }
    Ok(shortcut_id)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Stable shortcut IDs allow only a small, predictable character set.
    #[test]
    fn shortcut_id_validation_is_bounded() {
        assert_eq!(
            validate_shortcut_id("pick-color".to_string()).unwrap(),
            "pick-color"
        );
        assert!(validate_shortcut_id("".to_string()).is_err());
        assert!(validate_shortcut_id("bad.id".to_string()).is_err());
        assert!(validate_shortcut_id("x".repeat(65)).is_err());
    }

    /// Global shortcut state must recover the page event payload by native ID.
    #[test]
    #[cfg(not(target_os = "linux"))]
    fn shortcut_state_builds_event_payload() {
        let state = ShortcutState::new();
        {
            let mut inner = state.lock().unwrap();
            inner.by_id.insert(
                "capture".to_string(),
                RegisteredShortcut {
                    accelerator: "Control+Alt+KeyX".to_string(),
                    native_id: 7,
                },
            );
            inner.by_native_id.insert(7, "capture".to_string());
        }

        let event = state.event_for_native_id(7).unwrap().unwrap();
        assert_eq!(event.shortcut_id, "capture");
        assert_eq!(event.accelerator, "Control+Alt+KeyX");
        assert!(state.event_for_native_id(8).unwrap().is_none());
    }
}

/// Wayland request operations shared with the command entry points.
#[cfg(target_os = "linux")]
pub(crate) use super::shortcut_portal::Operation as PortalOperation;

/// Dispatches asynchronous portal registration on native Wayland.
#[cfg(target_os = "linux")]
pub(crate) async fn wayland(app: AppHandle, operation: PortalOperation) -> Result<bool, String> {
    super::shortcut_portal::execute(app, operation).await
}

/// Linux registrations live exclusively in the bounded portal actor.
#[cfg(target_os = "linux")]
pub struct ShortcutState;
#[cfg(target_os = "linux")]
impl ShortcutState {
    /// Construct the marker without initializing an X11 hotkey manager.
    pub fn new() -> Self {
        Self
    }
}
