[package]
name = "video"
version = "1.0.0"
authors = ["Lifeng Yan"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/bt-lang/bt"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bt-extension-sdk = { path = "../../crates/bt-extension-sdk", features = ["host-process"] }
serde_json = "=1.0.151"

[workspace]

[lints.rust]
warnings = "deny"
