//! BT Modbus protocol auxiliary library.
//!
//! This module builds Modbus RTU/TCP frames, verifies CRCs, and parses responses without owning serial or TCP connections.
//! Scripts can send the generated Bytes through `serial.write()`, `tcp.write()`, or another binary channel, leaving wait, retry,
//! and timeout policies at the I/O boundary.

use crate::libs::bytes;
use crate::value::Value;
use indexmap::IndexMap;
use std::cell::RefCell;
use std::rc::Rc;

/// Modbus standard library object.
#[derive(Debug, Clone, PartialEq)]
pub struct BtModbus;

impl BtModbus {
    /// Creates a Modbus standard library object.
    pub fn new(_args: Vec<Value>) -> Result<Value, String> {
        Ok(Value::Modbus(Self))
    }

    /// Calls the Modbus method.
    pub fn call_method(&self, method: &str, args: Vec<Value>) -> Result<Value, String> {
        match method {
            "rtu_request" => rtu_request(args),
            "tcp_request" => tcp_request(args),
            "parse_rtu" => parse_rtu(args),
            "parse_tcp" => parse_tcp(args),
            "crc16" => crc16_value(args),
            _ => Err(format!("modbus has no method `{}`", method)),
        }
    }
}

/// Constructs Modbus RTU request frame.
fn rtu_request(args: Vec<Value>) -> Result<Value, String> {
    let config = required_config(args.first(), "modbus.rtu_request")?;
    let unit_id = object_u8(config, "unit_id", 1, "modbus.rtu_request")?;
    let pdu = build_pdu(config, "modbus.rtu_request")?;
    let total = 1usize.saturating_add(pdu.len()).saturating_add(2);
    bytes::limit().and_then(|limit| {
        if total > limit {
            Err(format!(
                "modbus.rtu_request: byte length {} exceeds BT_BYTES_LIMIT {}",
                total, limit
            ))
        } else {
            Ok(limit)
        }
    })?;
    let mut frame = Vec::with_capacity(total);
    frame.push(unit_id);
    frame.extend_from_slice(&pdu);
    let crc = crc16_raw(&frame);
    frame.push((crc & 0x00ff) as u8);
    frame.push((crc >> 8) as u8);
    bytes::from_vec(frame)
}

/// Constructs Modbus TCP request frame.
fn tcp_request(args: Vec<Value>) -> Result<Value, String> {
    let config = required_config(args.first(), "modbus.tcp_request")?;
    let transaction_id = object_u16(config, "transaction_id", 1, "modbus.tcp_request")?;
    let protocol_id = object_u16(config, "protocol_id", 0, "modbus.tcp_request")?;
    let unit_id = object_u8(config, "unit_id", 1, "modbus.tcp_request")?;
    let pdu = build_pdu(config, "modbus.tcp_request")?;
    let length = 1usize.saturating_add(pdu.len());
    if length > u16::MAX as usize {
        return Err("modbus.tcp_request: PDU too large".to_string());
    }
    let total = 7usize.saturating_add(pdu.len());
    bytes::limit().and_then(|limit| {
        if total > limit {
            Err(format!(
                "modbus.tcp_request: byte length {} exceeds BT_BYTES_LIMIT {}",
                total, limit
            ))
        } else {
            Ok(limit)
        }
    })?;
    let mut frame = Vec::with_capacity(total);
    push_u16(&mut frame, transaction_id);
    push_u16(&mut frame, protocol_id);
    push_u16(&mut frame, length as u16);
    frame.push(unit_id);
    frame.extend_from_slice(&pdu);
    bytes::from_vec(frame)
}

/// Parses Modbus RTU response frames.
fn parse_rtu(args: Vec<Value>) -> Result<Value, String> {
    let data = required_bytes(args.first(), "modbus.parse_rtu")?;
    if data.len() < 5 {
        return Err("modbus.parse_rtu: RTU frame must contain at least 5 bytes".to_string());
    }
    let payload_len = data.len() - 2;
    let expected_crc = crc16_raw(&data[..payload_len]);
    let received_crc = u16::from_le_bytes([data[payload_len], data[payload_len + 1]]);

    let mut object = IndexMap::new();
    object.insert("protocol".to_string(), Value::Str("rtu".to_string()));
    object.insert("unit_id".to_string(), Value::Int(data[0] as i64));
    object.insert("crc".to_string(), Value::Int(received_crc as i64));
    object.insert("crc_expected".to_string(), Value::Int(expected_crc as i64));
    object.insert(
        "valid_crc".to_string(),
        Value::Bool(received_crc == expected_crc),
    );
    parse_pdu_into(&mut object, &data[1..payload_len])?;
    Ok(object_value(object))
}

/// Parses Modbus TCP response frames.
fn parse_tcp(args: Vec<Value>) -> Result<Value, String> {
    let data = required_bytes(args.first(), "modbus.parse_tcp")?;
    if data.len() < 8 {
        return Err("modbus.parse_tcp: TCP frame must contain at least 8 bytes".to_string());
    }
    let transaction_id = read_u16(&data, 0);
    let protocol_id = read_u16(&data, 2);
    let length = read_u16(&data, 4) as usize;
    if length == 0 {
        return Err("modbus.parse_tcp: MBAP length must be greater than 0".to_string());
    }
    let expected_len = 6usize.saturating_add(length);
    if data.len() < expected_len {
        return Err(format!(
            "modbus.parse_tcp: frame length {} is smaller than MBAP length {}",
            data.len(),
            expected_len
        ));
    }

    let mut object = IndexMap::new();
    object.insert("protocol".to_string(), Value::Str("tcp".to_string()));
    object.insert(
        "transaction_id".to_string(),
        Value::Int(transaction_id as i64),
    );
    object.insert("protocol_id".to_string(), Value::Int(protocol_id as i64));
    object.insert("length".to_string(), Value::Int(length as i64));
    object.insert(
        "valid_length".to_string(),
        Value::Bool(data.len() == expected_len),
    );
    object.insert("unit_id".to_string(), Value::Int(data[6] as i64));
    parse_pdu_into(&mut object, &data[7..expected_len])?;
    Ok(object_value(object))
}

/// Calculate Modbus RTU CRC16.
fn crc16_value(args: Vec<Value>) -> Result<Value, String> {
    let data = required_bytes(args.first(), "modbus.crc16")?;
    Ok(Value::Int(crc16_raw(&data) as i64))
}

/// Builds Modbus PDU.
fn build_pdu(config: &Value, method: &str) -> Result<Vec<u8>, String> {
    if let Some(value) = object_get(config, "pdu") {
        let pdu = bytes::value_to_byte_vec(&value, method)?;
        if pdu.is_empty() {
            return Err(format!("{}: pdu cannot be empty", method));
        }
        return Ok(pdu);
    }

    let function_code = object_function_code(config, method)?;
    let mut pdu = Vec::with_capacity(8);
    pdu.push(function_code);
    match function_code {
        1 | 2 => {
            let address = object_u16(config, "address", 0, method)?;
            let quantity = object_quantity(config, 1, 2000, method)?;
            push_u16(&mut pdu, address);
            push_u16(&mut pdu, quantity);
        }
        3 | 4 => {
            let address = object_u16(config, "address", 0, method)?;
            let quantity = object_quantity(config, 1, 125, method)?;
            push_u16(&mut pdu, address);
            push_u16(&mut pdu, quantity);
        }
        5 => {
            let address = object_u16(config, "address", 0, method)?;
            let value = if object_get(config, "value")
                .map(|value| value.is_truthy())
                .unwrap_or(false)
            {
                0xff00
            } else {
                0x0000
            };
            push_u16(&mut pdu, address);
            push_u16(&mut pdu, value);
        }
        6 => {
            let address = object_u16(config, "address", 0, method)?;
            let value = object_u16(config, "value", 0, method)?;
            push_u16(&mut pdu, address);
            push_u16(&mut pdu, value);
        }
        15 => build_write_multiple_coils(config, method, &mut pdu)?,
        16 => build_write_multiple_registers(config, method, &mut pdu)?,
        _ => {
            let data = object_get(config, "data").ok_or_else(|| {
                format!(
                    "{}: unsupported function_code `{}` needs data",
                    method, function_code
                )
            })?;
            let data = bytes::value_to_bytes(&data, method)?;
            pdu.extend_from_slice(data.as_ref());
        }
    }
    Ok(pdu)
}

/// Build and write multiple coil PDUs.
fn build_write_multiple_coils(
    config: &Value,
    method: &str,
    pdu: &mut Vec<u8>,
) -> Result<(), String> {
    let address = object_u16(config, "address", 0, method)?;
    let values = object_array(config, "values");
    if values.is_empty() {
        return Err(format!("{}: values cannot be empty", method));
    }
    if values.len() > 1968 {
        return Err(format!("{}: coil values length cannot exceed 1968", method));
    }
    push_u16(pdu, address);
    push_u16(pdu, values.len() as u16);
    let byte_count = values.len().div_ceil(8);
    pdu.push(byte_count as u8);
    for chunk in values.chunks(8) {
        let mut byte = 0u8;
        for (index, value) in chunk.iter().enumerate() {
            if value.is_truthy() {
                byte |= 1 << index;
            }
        }
        pdu.push(byte);
    }
    Ok(())
}

/// Constructs a write multiple register PDU.
fn build_write_multiple_registers(
    config: &Value,
    method: &str,
    pdu: &mut Vec<u8>,
) -> Result<(), String> {
    let address = object_u16(config, "address", 0, method)?;
    let values = object_array(config, "values");
    if values.is_empty() {
        return Err(format!("{}: values cannot be empty", method));
    }
    if values.len() > 123 {
        return Err(format!(
            "{}: register values length cannot exceed 123",
            method
        ));
    }
    push_u16(pdu, address);
    push_u16(pdu, values.len() as u16);
    pdu.push((values.len() * 2) as u8);
    for value in values {
        let value = u16_from_value(&value, "values", method)?;
        push_u16(pdu, value);
    }
    Ok(())
}

/// Parses PDU into objects.
fn parse_pdu_into(object: &mut IndexMap<String, Value>, pdu: &[u8]) -> Result<(), String> {
    if pdu.is_empty() {
        return Err("modbus parse: PDU cannot be empty".to_string());
    }
    let function_code = pdu[0];
    let exception = function_code & 0x80 != 0;
    object.insert(
        "function_code".to_string(),
        Value::Int(function_code as i64),
    );
    object.insert("exception".to_string(), Value::Bool(exception));
    if exception {
        object.insert(
            "exception_code".to_string(),
            pdu.get(1)
                .copied()
                .map(|value| Value::Int(value as i64))
                .unwrap_or(Value::Empty),
        );
        object.insert("data".to_string(), bytes::from_vec(pdu[1..].to_vec())?);
        return Ok(());
    }

    object.insert("data".to_string(), bytes::from_vec(pdu[1..].to_vec())?);
    match function_code {
        1 | 2 => parse_coils_into(object, pdu)?,
        3 | 4 => parse_registers_into(object, pdu)?,
        5 | 6 | 15 | 16 => parse_write_ack_into(object, pdu)?,
        _ => {}
    }
    Ok(())
}

/// Parses the coil read response.
fn parse_coils_into(object: &mut IndexMap<String, Value>, pdu: &[u8]) -> Result<(), String> {
    if pdu.len() < 2 {
        return Ok(());
    }
    let byte_count = pdu[1] as usize;
    if pdu.len() < 2 + byte_count {
        return Ok(());
    }
    object.insert("byte_count".to_string(), Value::Int(byte_count as i64));
    let mut coils = Vec::with_capacity(byte_count * 8);
    for byte in &pdu[2..2 + byte_count] {
        for bit in 0..8 {
            coils.push(Value::Bool(byte & (1 << bit) != 0));
        }
    }
    object.insert(
        "coils".to_string(),
        Value::Array(Rc::new(RefCell::new(coils))),
    );
    Ok(())
}

/// Parses the register read response.
fn parse_registers_into(object: &mut IndexMap<String, Value>, pdu: &[u8]) -> Result<(), String> {
    if pdu.len() < 2 {
        return Ok(());
    }
    let byte_count = pdu[1] as usize;
    if pdu.len() < 2 + byte_count {
        return Ok(());
    }
    object.insert("byte_count".to_string(), Value::Int(byte_count as i64));
    let mut registers = Vec::with_capacity(byte_count / 2);
    for chunk in pdu[2..2 + byte_count].chunks_exact(2) {
        registers.push(Value::Int(u16::from_be_bytes([chunk[0], chunk[1]]) as i64));
    }
    object.insert(
        "registers".to_string(),
        Value::Array(Rc::new(RefCell::new(registers))),
    );
    Ok(())
}

/// Parses the write confirmation response.
fn parse_write_ack_into(object: &mut IndexMap<String, Value>, pdu: &[u8]) -> Result<(), String> {
    if pdu.len() < 5 {
        return Ok(());
    }
    object.insert("address".to_string(), Value::Int(read_u16(pdu, 1) as i64));
    object.insert("value".to_string(), Value::Int(read_u16(pdu, 3) as i64));
    Ok(())
}

/// Read the configuration object.
fn required_config<'a>(value: Option<&'a Value>, method: &str) -> Result<&'a Value, String> {
    let Some(value @ Value::Object(_)) = value else {
        return Err(format!("{} requires a configuration object", method));
    };
    Ok(value)
}

/// Reads a required binary input argument.
fn required_bytes(value: Option<&Value>, method: &str) -> Result<Vec<u8>, String> {
    let value = value.ok_or_else(|| format!("{} requires a data argument", method))?;
    bytes::value_to_byte_vec(value, method)
}

/// Read object fields.
fn object_get(value: &Value, key: &str) -> Option<Value> {
    let Value::Object(values) = value else {
        return None;
    };
    values.borrow().get(key).cloned()
}

/// Read object array field.
fn object_array(value: &Value, key: &str) -> Vec<Value> {
    match object_get(value, key) {
        Some(Value::Array(values)) => values.borrow().clone(),
        _ => Vec::new(),
    }
}

/// Reads a `u8` object field.
fn object_u8(value: &Value, key: &str, default: u8, method: &str) -> Result<u8, String> {
    match object_get(value, key) {
        Some(value) => {
            let value = value.to_i64_lossy();
            if (0..=u8::MAX as i64).contains(&value) {
                Ok(value as u8)
            } else {
                Err(format!("{}: invalid `{}` value `{}`", method, key, value))
            }
        }
        None => Ok(default),
    }
}

/// Reads a `u16` object field.
fn object_u16(value: &Value, key: &str, default: u16, method: &str) -> Result<u16, String> {
    match object_get(value, key) {
        Some(value) => u16_from_value(&value, key, method),
        None => Ok(default),
    }
}

/// Read the request quantity field.
fn object_quantity(value: &Value, min: u16, max: u16, method: &str) -> Result<u16, String> {
    let quantity = object_u16(value, "quantity", 1, method)?;
    if quantity < min || quantity > max {
        return Err(format!(
            "{}: quantity must be in {}..={}, current {}",
            method, min, max, quantity
        ));
    }
    Ok(quantity)
}

/// Read u16 from script value.
fn u16_from_value(value: &Value, key: &str, method: &str) -> Result<u16, String> {
    let value = value.to_i64_lossy();
    if (0..=u16::MAX as i64).contains(&value) {
        Ok(value as u16)
    } else {
        Err(format!("{}: invalid `{}` value `{}`", method, key, value))
    }
}

/// Read function code.
fn object_function_code(value: &Value, method: &str) -> Result<u8, String> {
    let value = object_get(value, "function_code")
        .or_else(|| object_get(value, "function"))
        .ok_or_else(|| format!("{}: missing required field `function_code`", method))?;
    match value {
        Value::Str(name) => function_name_code(&name)
            .ok_or_else(|| format!("{}: unsupported function `{}`", method, name)),
        other => object_u8(&object_with_value(other), "value", 0, method),
    }
}

/// Wraps one value in an object and reuses `u8` validation.
fn object_with_value(value: Value) -> Value {
    let mut object = IndexMap::new();
    object.insert("value".to_string(), value);
    object_value(object)
}

/// Modbus function name to function code.
fn function_name_code(name: &str) -> Option<u8> {
    match name {
        "read_coils" => Some(1),
        "read_discrete_inputs" => Some(2),
        "read_holding_registers" => Some(3),
        "read_input_registers" => Some(4),
        "write_single_coil" => Some(5),
        "write_single_register" => Some(6),
        "write_multiple_coils" => Some(15),
        "write_multiple_registers" => Some(16),
        _ => None,
    }
}

/// Append big-endian u16.
fn push_u16(output: &mut Vec<u8>, value: u16) {
    output.extend_from_slice(&value.to_be_bytes());
}

/// Reads a big-endian `u16`.
fn read_u16(data: &[u8], offset: usize) -> u16 {
    u16::from_be_bytes([data[offset], data[offset + 1]])
}

/// Calculate Modbus RTU CRC16.
fn crc16_raw(data: &[u8]) -> u16 {
    let mut crc = 0xffffu16;
    for byte in data {
        crc ^= *byte as u16;
        for _ in 0..8 {
            if crc & 0x0001 != 0 {
                crc = (crc >> 1) ^ 0xa001;
            } else {
                crc >>= 1;
            }
        }
    }
    crc
}

/// Constructs a normal object value.
fn object_value(object: IndexMap<String, Value>) -> Value {
    Value::Object(Rc::new(RefCell::new(object)))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn modbus_crc16_matches_known_request() {
        let data = vec![0x01, 0x03, 0x00, 0x00, 0x00, 0x0a];
        assert_eq!(crc16_raw(&data), 0xcdc5);
    }

    #[test]
    fn modbus_rtu_request_builds_read_holding_frame() {
        let mut config = IndexMap::new();
        config.insert("unit_id".to_string(), Value::Int(1));
        config.insert(
            "function".to_string(),
            Value::Str("read_holding_registers".to_string()),
        );
        config.insert("address".to_string(), Value::Int(0));
        config.insert("quantity".to_string(), Value::Int(2));
        let value = rtu_request(vec![object_value(config)])
            .expect("should be able to construct RTU requests");
        let Value::Bytes(bytes) = value else {
            panic!("should return Bytes");
        };
        assert_eq!(bytes.to_hex_string(""), "010300000002c40b");
    }

    #[test]
    fn modbus_tcp_response_parses_registers() {
        let response = vec![0, 1, 0, 0, 0, 7, 1, 3, 4, 0, 10, 0, 20];
        let value = parse_tcp(vec![bytes::from_vec(response).unwrap()])
            .expect("should be able to parse TCP responses");
        let Value::Object(object) = value else {
            panic!("should return an object");
        };
        let object = object.borrow();
        assert_eq!(object.get("function_code"), Some(&Value::Int(3)));
        let Some(Value::Array(registers)) = object.get("registers") else {
            panic!("should return a register array");
        };
        assert_eq!(
            registers.borrow().as_slice(),
            &[Value::Int(10), Value::Int(20)]
        );
    }
}
