[package]
name = "bt-extension-sdk"
version = "0.1.0"
authors = ["Lifeng Yan"]
license = "MIT OR Apache-2.0"
homepage = "https://btlang.org"
repository = "https://github.com/bt-lang/bt"
edition = "2021"
publish = false

[lints]
workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
serde_json = { version = "=1.0.151", optional = true }

[target.'cfg(unix)'.dependencies]
libc = { version = "=0.2.189", optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "=0.61.2", optional = true, features = ["Win32_Foundation", "Win32_Security", "Win32_System_JobObjects", "Win32_System_Threading"] }

[features]
host-process = ["dep:serde_json", "dep:libc", "dep:windows-sys"]
